export const GET_BANNERS = 'GET_BANNERS';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE';

export const SET_LOADING = 'SET_LOADING_BANNER';
export const REMOVE_LOADING = 'REMOVE_LOADING_BANNER';
