export const SET_LOADING = 'SET_LOADING_CATEGORY';
export const REMOVE_LOADING = 'REMOVE_LOADING_CATEGORY';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
