export const GET_DATA = 'GET_PRODUCT_DETAIL';
export const GET_DATA_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_DATA_FAILURE = 'GET_PRODUCT_DETAIL_FAILURE';

export const SET_LOADING = 'SET_LOADING_PRODUCT_DETAIL';
export const REMOVE_LOADING = 'REMOVE_LOADING_PRODUCT_DETAIL';

export const RATE_PRODUCT = 'RATE_PRODUCT';
export const RATE_PRODUCT_SUCCESS = 'RATE_PRODUCT_SUCCESS';
export const RATE_PRODUCT_FAILURE = 'RATE_PRODUCT_FAILURE';

export const REVIEW_PRODUCT = 'REVIEW_PRODUCT';
export const REVIEW_PRODUCT_SUCCESS = 'REVIEW_PRODUCT_SUCCESS';
export const REVIEW_PRODUCT_FAILURE = 'REVIEW_PRODUCT_FAILURE';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';

export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';

export const LIKE_REVIEW = 'LIKE_REVIEW';
export const LIKE_REVIEW_SUCCESS = 'LIKE_REVIEW_SUCCESS';

export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';

export const LIKE_ANSWER = 'LIKE_ANSWER';
export const LIKE_ANSWER_SUCCESS = 'LIKE_ANSWER_SUCCESS';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS';
