export const SET_LOADING = 'SET_LOADING_PRODUCT';
export const REMOVE_LOADING = 'REMOVE_LOADING_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
